{{- if .Values.version1.enabled -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "5000"
    prometheus.io/scrape: "true"
  name: {{ include "ab-testing.fullname" . }}-1
  labels:
    {{- include "ab-testing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ab-testing.selectorLabels" . | nindent 4 }}
    version: 1.0.0
{{- end }}