

grafana:
  ingress: 
    annotations: 
      kubernetes.io/ingress.class: nginx-public
      kubernetes.io/tls-acme: "true"
    enabled: true
    hosts: 
      - "grafana-deploymentstrategies-demo.cluster.local"
  persistence: 
    enabled: true
    size: "1Gi"
  grafana.ini:
    analytics:
      check_for_updates: true
    grafana_net:
      url: https://grafana-deploymentstrategies-demo.cluster.local
    log:
      mode: console
    paths:
      data: /var/lib/grafana/data
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
  datasources: 
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://basicsetup-prometheus-server
        access: proxy
        isDefault: true
  sidecar:
    dashboards:
      enabled: true

prometheus:
  alertmanager:
    enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  pushgateway:
    enabled: false
  server:
    persistentVolume:
      enabled: false
    global:
      scrape_interval: 10s